added invisibility potion
Terasology/Potions pull request #17
Opened 2016-12-09 15:40 UTC by apaukraine

2016-12-09 20:05 UTC, rzats requested changes
The potion has to actually make the player invisible :) To do that, you'll need to declare an effect - INVIS - in ([PotionCommonEffects](https://github.com/Terasology/Potions/blob/master/src/main/java/org/terasology/potions/PotionCommonEffects.java)) and code its' functionality (in [DrinkPotionAuthoritySystem](https://github.com/Terasology/Potions/blob/master/src/main/java/org/terasology/potions/system/DrinkPotionAuthoritySystem.java)).

Also, the art is a little odd - that's an invisibility _cloak_, not a potion! I'd change it to a spectral-looking bottle.

2016-12-09 20:05 UTC, rzats commented on README.md
> -* Explosive - When the player uses this on an object, it triggers an explosion.
This shouldn't be removed.

2016-12-09 20:05 UTC, rzats commented on module.txt
> +    "author" : "bi0hax, XTariq, shardulc, apaukraine",
These shouldn't be removed.

2017-01-23 15:19 UTC, smsunarto commented
Closed for inactivity - @apaukraine Please update your fork and re-open when you are willing to continue this PR.

2017-01-23 15:19 UTC, closed without merging