Added BlindWalk potion for Google Code In 2016
Terasology/Potions pull request #20
Opened 2016-12-11 15:21 UTC by digitalripperynr

Added BlindWalk potion - Turns the player blind for 5 seconds along with speed decrease.

2016-12-11 15:42 UTC, rzats requested changes
You'll actually have to implement the `NO_VISIBILITY` effect 🙂 For this you'll need to declare it in [`PotionCommonEffects`](https://github.com/Terasology/Potions/blob/master/src/main/java/org/terasology/potions/PotionCommonEffects.java), then implement in [`DrinkPotionAuthoritySystem`](https://github.com/Terasology/Potions/blob/master/src/main/java/org/terasology/potions/system/DrinkPotionAuthoritySystem.java).

2016-12-11 15:42 UTC, rzats commented on assets/prefabs/potion/BlindWalkPotion.prefab
> +			{
Also, the indentation here is a little odd - can you reformat the JSON file using IntelliJ?

2016-12-11 15:46 UTC, digitalripperynr commented on assets/prefabs/potion/BlindWalkPotion.prefab
> +			{
Thanks for the advice... I was a little confused at first on how all the effects were implemented.... Now its all clear... Thanks. Will update soon..

2016-12-11 16:17 UTC, digitalripperynr commented
Hey,
Even if I implement the 'No-Visibility' effect in common effects and potionauthoritysystem, there is no code to specify what the game has to do...

Please help

2016-12-11 16:25 UTC, rzats commented
That's correct - actually implementing the code is also part of the task 🙂

2016-12-11 16:33 UTC, digitalripperynr commented
Can you please give some idea on how to do that?

2016-12-11 17:05 UTC, rzats commented
I've done some research on this and found out that making the effect work requires on an API that's not yet merged (https://github.com/MovingBlocks/Terasology/pull/2449). Therefore, it's OK for you to submit a stub method/code block with a TODO note for later 🙂

2016-12-11 17:08 UTC, digitalripperynr commented
Thanks.
I'll do that for now.
But I figured out that I need to create an entire new file for the No_visibility effect and set it to render a black screen for the given amount of time. I will work on this later.

-Arpit

2016-12-12 05:20 UTC, Cervator requested changes
Heyo, few more tiny tweaks requested, although agreed on the effect implementation being problematic right at this moment so we can merge and approve in the meantime :-)

One additional note: the text on the potion icon will be *very* hard to see in-game (and even get reversed due to the way held items are rendered right now). Maybe just pick a color or simple icon? Maybe an outlined footprint (dashed line) instead

2016-12-12 05:20 UTC, Cervator commented on assets/prefabs/potion/BlindWalkPotion.prefab
> +		"effect": "NO_VISIBILITY"
A few stray tab characters here, please replace with spaces :)

2016-12-12 05:20 UTC, Cervator commented on src/main/java/org/terasology/potions/PotionCommonEffects.java
> +	public static final String NO_VISIBILITY = "NO_VISIBILITY";
Could you add something above this to indicate the pending effect implementation? Like:

`// TODO: Effect implementation awaiting API improvements, such as https://github.com/MovingBlocks/Terasology/pull/2449

2016-12-12 05:20 UTC, Cervator commented on src/main/java/org/terasology/potions/system/DrinkPotionAuthoritySystem.java
> +                    herbEffect = new NoVisibilityEffect();
Note that this class does not appear to be part of the PR. Forget to `git add` it? :-)

2016-12-12 05:21 UTC, Cervator commented
And just to echo @rzats yeah it'll be fine to submit a more or less blank stub class for `NoVisibilityEffect` - we just need the code to actually compile before we can merge it :D

2016-12-12 05:31 UTC, digitalripperynr commented on src/main/java/org/terasology/potions/system/DrinkPotionAuthoritySystem.java
> +                    herbEffect = new NoVisibilityEffect();
OK I get it I need to add a file for NoVisibilityEffect to the potions/effects directory....

Thanks

2016-12-12 06:21 UTC, digitalripperynr commented
Hey,
Please review the changes I made to the files.

Thanks
-Arpit

2016-12-13 02:32 UTC, Cervator requested changes
So at this point there's more small stuff that would be super easy to avoid if you were running out of IntelliJ and noticing its little recommendations. If you are at all able to get IntelliJ running with the source code showing in there that would be the best thing you could do right now :-)

Each issue is super easy to fix and I considered during it as part of the merge, but you really need to have a good setup to move forward with your coding adventure. Remember that IRC is available if you need help setting up!

2016-12-13 02:32 UTC, Cervator commented on src/main/java/org/terasology/potions/effect/NoVisibilityEffect.java
> +import org.terasology.entitySystem.entity.EntityManager;
Most of these imports are unused, should show gray and underlined in IntelliJ - please remove those :-)

2016-12-13 02:32 UTC, Cervator commented on src/main/java/org/terasology/potions/effect/NoVisibilityEffect.java
> +import org.terasology.logic.actions.*;
Wildcard imports are against our code style, although these will be removed anyway as unused. But if you configure IntelliJ right it'll avoid the wildcard imports / format them nicely in the future :-)

See http://stackoverflow.com/questions/3348816/intellij-never-use-wildcard-imports

2016-12-13 02:32 UTC, Cervator commented on src/main/java/org/terasology/potions/effect/NoVisibilityEffect.java
> +public class NoVisibilityEffect implements HerbEffect {
If you were compiling the code to make sure all was well you should've seen an error here. Like other effects even though this one is a placeholder pending API improvements anything implementing `HerbEffect` also must implement the `applyEffect` potion. Check out other effects to see how it should look - yours can probably be empty but needs to exist. It looks like you've got the Javadoc for it below, so maybe you just deleted the method header itself?

2016-12-13 02:32 UTC, Cervator commented on src/main/java/org/terasology/potions/effect/NoVisibilityEffect.java
> +	 Once the API for Custom Actions is implemented, the code for NoVisibility Effect goes here.
You have a couple tab characters here. Please replace with spaces :-)

2016-12-13 02:32 UTC, Cervator commented on src/main/java/org/terasology/potions/system/DrinkPotionAuthoritySystem.java
> +                    herbEffect = new NoVisibilityEffect();
You have the class now, but the DrinkPotionAuthoritySystem needs to import it before it'll be able to find it. Again something like IntelliJ should outright prompt you "Hey want to import this class from X?" :-) 

You also have tab characters again on the case statement line

2016-12-13 02:32 UTC, Cervator commented on README.md
> +* MegaJumpBottle.png, GigaJumpBottle.png edited from base by Patrick Wang
After this line you could put a quick note that "BlindWalkPotionBottle.png edited from base by digitalripperynr"

2016-12-13 08:20 UTC, digitalripperynr commented
Hey,
I apologise. I messed up everything.
Now installing IntelliJ.
I will close this PR and open a new one with all the changes (final this time).

Thanks
-Arpit

2016-12-14 08:30 UTC, digitalripperynr commented
I am closing this PR and opening a new one...

2016-12-14 08:30 UTC, closed without merging