GCI TASK (Add a new potion to the Potions module)(DhananjayGarg19)
Terasology/Potions pull request #28
Opened 2016-12-15 12:15 UTC by DhananjayGarg19

2016-12-16 03:54 UTC, Cervator commented
Hi @DhananjayGarg19! I am afraid this potion won't work, "Die" is not a registered effect and if it was I expect it should outright kill the player, not just subtract 10 HP.  In fact there is [an existing HarmPotion](https://github.com/Terasology/Potions/blob/master/assets/prefabs/potion/HarmPotion.prefab) that does that exact thing (just 4 HP) and works as it uses the valid (and well named) "HARM" effect.

Some suggestions:

* Make sure you set up to run from code properly so you can test the effects of a potion in-game
* Look at the available effects in `PotionCommonEffects` in the Potion module to get some inspiration for what can be done
* Consider whether you'd want to take on the challenge of writing an entirely new effect - we have some good examples at this point.

At a minimum I suggest correcting the effect name and increasing the magnitude to where it is more likely to kill the user. In that case you may also want to rename the potion to something like "DeathPotion" instead

2016-12-17 06:08 UTC, Avalancs commented on assets/prefabs/potion/DeathPotion.prefab
> +                "effect": "Death",
"Death" is not an existing effect, you still need to find the effect that harms the player in `PotionCommonEffects`.

2016-12-17 06:09 UTC, Avalancs commented on assets/prefabs/potion/DeathPotion.prefab
> +        "icon": "Potions:DeathPotionBottle",
For this to work, you need to rename the picture to DeathPotionBottle.png

2016-12-17 06:12 UTC, Avalancs requested changes
Please look at the two comments I added.

Also the picture you attached has a white background, which will not be transparent inside the game. We will make a wiki page on how to turn the background transparent soon.

2016-12-18 05:42 UTC, Cervator commented
Merged in https://github.com/Terasology/Potions/commit/6c4fe02a08e2bcec85ca4bc6dfa577f887476e9c with some fixes on top in https://github.com/Terasology/Potions/commit/ed234145f91398caabfedad914a05e2d1c9562d1 - closing as complete

2016-12-18 05:42 UTC, closed without merging